#### Architect
architect:
  - ulysseses

#### (Secret) Assets
assets:
  secret.csv: "ulysseses/secret-repo#assets/secret.csv"
# add @rultor into list of collabs into priv repo
# priv repo must contain .rultor.yml where the "friends" section
# should include the name of the repo where the assets are used,
# e.g.
#
# friends:
#   - ulysseses/stupid-project
#   - lolzors/*

#### Environment Variables
env:
  BOGUS_VAR: "lel"
merge:
  script:
    - echo "Script before merge"
    - python main.py
deploy:
  script:
    - echo "Script before deploy"
    - python main.py


  
